---
- name: docker deployment

  # hosts: webservers
  become: True
  hosts: locahost
  # gather_facts: no
  # become: yes
  # become_method: sudo
  # become_user: nobody

  tasks:
    - name: build main docker file
      command: docker build --rm -t ubuntu/main:test -f "/home/introversial/revision_docker/main/Dockerfile"

    - name: Run Docker Container
      command: docker run -d --name app -p 5000:5000 ubuntu/main:test